[workspace]
authors = ["Center for Research Computing and Data"]
channels = ["conda-forge"]
name = "user-manual"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = { cmd = ["properdocs", "build"] }
serve = { cmd = ["properdocs", "serve"] }

[dependencies]
properdocs = ">=1.6.7,<2"
mkdocs-material = ">=9.7.6,<10"
mkdocstrings = ">=1.0.4,<2"
mkdocs-video = ">=1.5.0,<2"
mkdocs-redirects = ">=1.2.3,<2"
